apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/

images:
  - name: skulkarniassyst/resume-parser  
    newName: skulkarniassyst/resume-parser 
    newTag: 02e2b7e