apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/

images:
  - name: resume-parser-frontend
    newName: https://hub.docker.com/repository/docker/skulkarniassyst/resume-parser
    newTag: 567b692