apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-parser-frontend
  template:
    metadata:
      labels:
        app: resume-parser-frontend
    spec:
      containers:
      - name: frontend
        image: skulkarniassyst/resume-parser-frontend:latest
        ports:
        - containerPort: 80
