apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: resume-parser-deployment
spec:
  selector:
    app: resume-parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

